ARG BASE_IMAGE=repo.irsl.eiiris.tut.ac.jp/irsl_system:one
FROM ${BASE_IMAGE}

###
RUN (cd /; git clone https://github.com/IRSL-tut/RoboManipBaselines.git --recursive)

WORKDIR /RoboManipBaselines

RUN apt update -q -qq && \
    apt install -q -qq -y ffmpeg python3-venv libnppicc12 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/

# RUN python3 -m venv /irsl_venv --copies --system-site-packages
RUN python3 -m venv /irsl_venv --copies

## install pytorch
RUN <<EOF
if [ -e /irsl_venv/bin/activate ]; then
   source /irsl_venv/bin/activate
fi

## iceoryx2 -> /opt/python
mkdir -p /opt/python
pip install --target /opt/python iceoryx2==0.7.0
pip install -U --index-url https://rocm.nightlies.amd.com/v2/gfx110X-all/ "rocm[libraries,devel]"
pip install -U --index-url https://rocm.nightlies.amd.com/v2/gfx110X-all/ torch torchaudio torchvision
EOF
# pip install -U --index-url https://rocm.nightlies.amd.com/v2/gfx110X-all/ --pre torch torchaudio torchvision

## copy local library
COPY irsl_manip_libs /opt/python/irsl_manip_libs

RUN source /irsl_venv/bin/activate && \
    cd /RoboManipBaselines && \
    pip install -e .[act]  && \
    cd third_party/act/detr && \
    pip install -e .

## add for fix torch version
#    sed -i -e 's@"torch"@"torch<2.9"@' pyproject.toml && \

## SARNN
RUN source /irsl_venv/bin/activate && \
    cd /RoboManipBaselines && \
    pip install -e .[sarnn] && \ 
    cd third_party/eipl && \
    pip install -e .

## Diffusion Policy
RUN apt update -q -qq && \
    apt install -q -qq -y libosmesa6-dev libglfw3 patchelf && \
    apt clean && \
    rm -rf /var/lib/apt/lists/
# libgl1-mesa-glx is not required in irsl_system
RUN source /irsl_venv/bin/activate && \
    cd /RoboManipBaselines && \
    pip install -e .[diffusion-policy] && \
    cd third_party/diffusion_policy && \
    pip install -e .

### patched by IRSL
RUN <<EOF
cd /RoboManipBaselines
cat - << _DOC_ | patch -p1
diff --git a/robo_manip_baselines/common/base/TrainBase.py b/robo_manip_baselines/common/base/TrainBase.py
index 5ef7ab7..4918b3d 100644
--- a/robo_manip_baselines/common/base/TrainBase.py
+++ b/robo_manip_baselines/common/base/TrainBase.py
@@ -168,7 +168,7 @@ class TrainBase(ABC):
         )
 
         parser.add_argument("--seed", type=int, default=42, help="random seed")
-
+        parser.add_argument("--save_interval", type=int, default=100, help="IRSL save_interval")
         self.set_additional_args(parser)
 
         if argv is None:
diff --git a/robo_manip_baselines/policy/act/TrainAct.py b/robo_manip_baselines/policy/act/TrainAct.py
index 78655d4..6140c10 100644
--- a/robo_manip_baselines/policy/act/TrainAct.py
+++ b/robo_manip_baselines/policy/act/TrainAct.py
@@ -97,8 +97,8 @@ class TrainAct(TrainBase):
                 self.update_best_ckpt(epoch_summary)
 
             # Save current checkpoint
-            if epoch % max(self.args.num_epochs // 10, 1) == 0:
-                self.save_current_ckpt(f"epoch{epoch:0>3}")
+            if epoch % min(self.args.save_interval, max(self.args.num_epochs // 10, 1)) == 0:
+                self.save_current_ckpt(f"epoch{epoch:0>5}")
 
         # Save last checkpoint
         self.save_current_ckpt("last")
diff --git a/robo_manip_baselines/policy/diffusion_policy/TrainDiffusionPolicy.py b/robo_manip_baselines/policy/diffusion_policy/TrainDiffusionPolicy.py
index 938e8db..5d3bac2 100644
--- a/robo_manip_baselines/policy/diffusion_policy/TrainDiffusionPolicy.py
+++ b/robo_manip_baselines/policy/diffusion_policy/TrainDiffusionPolicy.py
@@ -336,8 +336,8 @@ class TrainDiffusionPolicy(TrainBase):
             policy.train()
 
             # Save current checkpoint
-            if epoch % max(self.args.num_epochs // 10, 1) == 0:
-                self.save_current_ckpt(f"epoch{epoch:0>4}", policy=policy)
+            if epoch % min(self.args.save_interval, max(self.args.num_epochs // 10, 1)) == 0:
+                self.save_current_ckpt(f"epoch{epoch:0>5}", policy=policy)
 
         # Save last checkpoint
         self.save_current_ckpt("last", policy=policy)
diff --git a/robo_manip_baselines/policy/sarnn/TrainSarnn.py b/robo_manip_baselines/policy/sarnn/TrainSarnn.py
index 6f15a45..fc5c9fc 100644
--- a/robo_manip_baselines/policy/sarnn/TrainSarnn.py
+++ b/robo_manip_baselines/policy/sarnn/TrainSarnn.py
@@ -243,8 +243,8 @@ class TrainSarnn(TrainBase):
                 self.update_best_ckpt(epoch_summary)
 
             # Save current checkpoint
-            if epoch % max(self.args.num_epochs // 10, 1) == 0:
-                self.save_current_ckpt(f"epoch{epoch:0>4}")
+            if epoch % min(self.args.save_interval, max(self.args.num_epochs // 10, 1)) == 0:
+                self.save_current_ckpt(f"epoch{epoch:0>5}")
 
         # Save last checkpoint
         self.save_current_ckpt("last")
diff --git a/robo_manip_baselines/policy/act/RolloutAct.py b/robo_manip_baselines/policy/act/RolloutAct.py
index 894c739..092720c 100644
--- a/robo_manip_baselines/policy/act/RolloutAct.py
+++ b/robo_manip_baselines/policy/act/RolloutAct.py
@@ -20,7 +20,7 @@ class RolloutAct(RolloutBase):
             help="whether to disable temporal ensembling of the inferred policy",
         )
 
-    def setup_policy(self):
+    def setup_policy(self, device="cuda"):
         # Print policy information
         self.print_policy_info()
         print(
@@ -31,6 +31,7 @@ class RolloutAct(RolloutBase):
         DETRVAE.set_state_dim(self.state_dim)
         DETRVAE.set_action_dim(self.action_dim)
         self.policy = ACTPolicy(self.model_meta_info["policy"]["args"])
+        self.policy.to(device)
 
         # Register fook to visualize attention images
         def forward_fook(_layer, _input, _output):
@@ -43,7 +44,7 @@ class RolloutAct(RolloutBase):
             layer.self_attn.register_forward_hook(forward_fook)
 
         # Load checkpoint
-        self.load_ckpt()
+        self.load_ckpt(device)
 
     def setup_plot(self):
         fig_ax = plt.subplots(
_DOC_
EOF
